apiVersion: apps/v1
kind: Deployment
metadata:
  name: giffy-deploy
spec:
  selector:
    matchLabels:
      app: giffy-app
  replicas: 2
  template:
    metadata:
      labels:
        app: giffy-app
    spec:
      containers:
      - name: giffy
        image: augustodelg/giffy-test:0.1
        ports:
        - containerPort: 8080
