apiVersion: v1
kind: Service
metadata:
  name: giffy-service
spec:
  selector:
    app: giffy-deploy
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: giffy-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
     app: giffy-deploy
  

